openapi: 3.0.3
info:
  title: WS LamineIA - OpenAPI 3.0  
  version: 0.0.1
servers:  
  - url: http://localhost:4800     
  - url: https://wslamineia.academys.io:4800
tags:
  - name: auth
    description: Identification   
  - name: user
    description: Administration   
  - name: subscribers
    description: Administration   
  - name: paymenttype
    description: Administration 
  - name: chat
    description: Administration
  - name: paymentdetails
    description: Administration   
  - name: loghistory
    description: Administration     
paths:
  # module login
  /ws/auth/login:
    post:
      tags:
        - auth
      summary: Login
      description: Session Start.
      operationId: sendLogin
      requestBody:
        description: Init Session
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendLogin'   
        required: true         
      responses:
        '200':
          description: Ok...!         
        '400':
          description: validation error
  # modulo login      

  # modulo user       
  /ws/user:
    get:
      tags:
        - user
      summary: Get One user.
      description:  One user.
      operationId: userGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - user
      summary: Create user.
      description: New user.       
      operationId: adduser
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/adduser'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    put:
      tags:
        - user
      summary: Update user.
      description: Modify user.       
      operationId: updateuser
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateuser'   
        required: true         
      responses:
        '200':
          description: Ok / Update user...!
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!  
    delete:
      tags:
        - user
      summary: Delete user.
      description: delete 
      operationId: deleteuser.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!    
  # modulo user 

  # modulo subscribers       
  /ws/subscribers:
    get:
      tags:
        - subscribers
      summary: Get One subscribers.
      description:  One subscribers.
      operationId: userGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - subscribers
      summary: Create subscribers.
      description: New subscribers.       
      operationId: addsubscribers
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addsubscribers'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    
    delete:
      tags:
        - subscribers
      summary: Delete subscribers.
      description: delete 
      operationId: deletesubscribers.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!
  /ws/subscribers/list:
    get:
      tags:
        - subscribers
      summary: Get All subscribers.
      description:  All subscribers.
      operationId: userGetAll    
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!      
  # modulo subscribers

  # modulo paymenttype 

  /ws/paymenttype:
    get:
      tags:
        - paymenttype
      summary: Get One paymenttype.
      description:  One paymenttype.
      operationId: userGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - paymenttype
      summary: Create paymenttype.
      description: New paymenttype.       
      operationId: addpaymenttype.
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addpaymenttype'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    put:
      tags:
        - paymenttype
      summary: Update paymenttype.
      description: Modify paymenttype.       
      operationId: updatepaymenttype
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatepaymenttype'   
        required: true         
      responses:
        '200':
          description: Ok / Update user...!
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!  
    delete:
      tags:
        - paymenttype
      summary: Delete paymenttype.
      description: delete 
      operationId: deletepaymenttype.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!
  /ws/paymenttype/list:
    get:
      tags:
        - paymenttype
      summary: Get All paymenttype.
      description:  All paymenttype.
      operationId: paymenttypeGetAll      
      responses:
        '200':
          description: Ok...!
        '210':
          description: getAll - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!          
          
          # Modulo paymenttype 
         
          # Modulo chat 
   
  /ws/chat:      
    post:
      tags:
        - chat
      summary: chat.
      description: New chat.       
      operationId: newchat.
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newchat'   
        required: true         
      responses:
        '200':
          description: Success...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!   

          #Modulo chat 

# modulo paymentdetails

  /ws/paymentdetails:
    get:
      tags:
        - paymentdetails
      summary: Get One paymentdetails.
      description:  One paymentdetails.
      operationId: userGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - paymentdetails
      summary: Create paymentdetails.
      description: New paymentdetails.       
      operationId: addpaymentdetails.
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addpaymentdetails'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    put:
      tags:
        - paymentdetails
      summary: Update paymentdetails.
      description: Modify paymentdetails.       
      operationId: updatepaymentdetails
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatepaymentdetails'   
        required: true         
      responses:
        '200':
          description: Ok / Update user...!
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!  
    delete:
      tags:
        - paymentdetails
      summary: Delete paymentdetails.
      description: delete 
      operationId: deletepaymentdetails.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!
  /ws/paymentdetails/list:
    get:
      tags:
        - paymentdetails
      summary: Get All paymentdetails.
      description:  All paymentdetails.
      operationId: paymentdetailsGetAll      
      responses:
        '200':
          description: Ok...!
        '210':
          description: getAll - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!          
          
          # Modulo paymentdetails

  /ws/paymentdetails/confirm: 
    put:
      tags:
        - paymentdetails
      summary: confirm paymentdetails.
      description: confirm paymentdetails.       
      operationId: confirmpaymentdetails
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/confirmpaymentdetails'   
        required: true         
      responses:
        '200':
          description: Ok / confirm ...!
        '210':
          description: subscriber not found 
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!   

          # modulo paymentdetails  

  /ws/loghistory:
    get:
      tags:
        - loghistory
      summary: Get One loghistory.
      description:  One loghistory.
      operationId: userGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - loghistory
      summary: Create loghistory.
      description: New loghistory.       
      operationId: addloghistory.
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addloghistory'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    put:
      tags:
        - loghistory
      summary: Update loghistory.
      description: Modify loghistory.       
      operationId: updateloghistory
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateloghistory'   
        required: true         
      responses:
        '200':
          description: Ok / Update user...!
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!  
    delete:
      tags:
        - loghistory
      summary: Delete loghistory.
      description: loghistory 
      operationId: deleteloghistory.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!
  /ws/loghistory/list:
    get:
      tags:
        - loghistory
      summary: Get All loghistory.
      description:  All loghistory.
      operationId: loghistoryGetAll      
      responses:
        '200':
          description: Ok...!
        '210':
          description: getAll - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!          
          
          # Modulo loghistory
                 

#//////////////////////////////////////////////////////////////////////////////////////////     

components:
  schemas:
    sendLogin:
      type: object
      properties:
        email:
          type: string          
          example: user@gmail.com
        otp:
          type: string
          example: 123456
    adduser:
      type: object
      properties:
        email:
          type: string          
          example: "user@gmail.com"
    updateuser:
      type: object
      properties:
        id:
          type: integer
          example: 100
        email:
          type: string          
          example: "user@gmail.com"
  
    addsubscribers:
          type: object
          properties:
            idUser:
              type: integer     
              example: 1
            period:
              type: string 
              example: "2026-12-31"
            apiKey: 
              type: string
              example: "gr5g18g5s1gv53s1dv8sd4g"
    addpaymenttype:
          type: object
          properties:
            name:
              type: string    
              example: "paypal"
            paymentGateway:
              type: string 
              example: "paypal"
    updatepaymenttype:
          type: object
          properties:
            id:
              type: integer   
              example: 1
            name:
              type: string 
              example: "paypal" 
            paymentGateway:
              type: string  
              example: "paypal"
            status:
              type: integer 
              example: 1
    newchat:
          type: object
          properties:
            message:
              type: string    
              example: "Que dia es hoy?"
            intelligence:
              type: string 
              example: "groq - huggingface"  
    addpaymentdetails:
          type: object
          properties:
            idSubscribers:
              type: integer   
              example: 1
            idPayMethod:
              type: integer
              example: 1
            amount:
              type: string
              example: "1.1"       
    updatepaymentdetails:
          type: object
          properties:
            id:
              type: integer   
              example: 0
            idSubscribers:
              type: integer
              example: 0
            idPayMethod:
              type: integer  
              example: 0
            amount:
              type: string 
              example: "1.1"         
    confirmpaymentdetails:
          type: object
          properties:
            id:
              type: integer   
              example: 0
    addloghistory:
          type: object
          properties:
            idUser:
              type: integer   
              example: 0
            uuId:
              type: string
              example: "abc123"
            message:
              type: string
              example: "message" 
            type:
              type: integer
              example: 0        
    updateloghistory:
          type: object
          properties:
            id:
              type: integer   
              example: 0
            idUser:
              type: integer
              example: 0
            uuId:
              type: string 
              example: "abc123"
            message:
              type: string 
              example: "message" 
            type:
              type: integer  
              example: 0          
            
                                   



    changeStatus:
      type: object
      properties:
        id:
          type: integer          
          example: 15    
        status:
          type: integer          
          example: 1        
      type: object

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer                     
         

security:
  - bearerAuth: []
