openapi: 3.0.3
info:
  title: WS Elearning Dev - OpenAPI 3.0  
  version: 0.0.1
servers:  
  - url: http://localhost:3000     
  - url: https://wselearnigdev.gosmartcrm.com:3000
tags:
  - name: auth
    description: Identification   
  - name: test
    description: Administration   
paths:
  # module login
  /ws/auth/login:
    post:
      tags:
        - auth
      summary: Login
      description: Session Start.
      operationId: login
      requestBody:
        description: Init Session
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendLogin'   
        required: true         
      responses:
        '200':
          description: Ok...!         
        '400':
          description: validation error
  # modulo login      

  # modulo test       
  /ws/test:
    get:
      tags:
        - test
      summary: Get One test.
      description:  One test.
      operationId: testGetOne   
      parameters:          
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true   
      responses:
        '200':
          description: Ok...!
        '210':
          description: getOne - empty...!
        '400':
          description: validation error  
        '403':
          description: Access Denied...!  
    post:
      tags:
        - test
      summary: Create test.
      description: New test.       
      operationId: addtest
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addtest'   
        required: true         
      responses:
        '201':
          description: Created...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!  
    put:
      tags:
        - test
      summary: Update test.
      description: Modify test.       
      operationId: updatetest
      requestBody:        
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatetest'   
        required: true         
      responses:
        '200':
          description: Ok / Update test...!
        '400':
          description: validation error / Sql Errors
        '403':
          description: Access Denied...!  
    delete:
      tags:
        - test
      summary: Delete test.
      description: delete 
      operationId: deletetest.
      parameters:         
        - in: query
          name: id
          schema:
            type: integer 
            example : 0
          required: true             
      responses:
        '200':
          description: Ok...!
        '400':
          description: validation error
        '403':
          description: Access Denied...!    
  # modulo test 
#//////////////////////////////////////////////////////////////////////////////////////////          
components:
  schemas:
    sendLogin:
      type: object
      properties:
        email:
          type: string          
          example: memberjhondow
        otp:
          type: string
          example: clavedow
    addtest:
      type: object
      properties:
        idCompany:
          type: integer          
          example: 0
        idVideo:
          type: integer
          example: 0
        typetest:
          type: integer
          example: 0
        title:
          type: string
          example: test title  
        description:
          type: string
          example: test description 
        pathImage:
          type: string
          example: test/0  
        urlImage:
          type: string
          example: http://url.com/test/0  
    updatetest:
      type: object
      properties:
        idCompany:
          type: integer          
          example: 0
        idVideo:
          type: integer
          example: 0
        typetest:
          type: integer
          example: 0
        title:
          type: string
          example: test title  
        description:
          type: string
          example: test description 
        pathImage:
          type: string
          example: test/0  
        urlImage:
          type: string
          example: http://url.com/test/0  
 
    changeStatus:
      type: object
      properties:
        id:
          type: integer          
          example: 15    
        status:
          type: integer          
          example: 1        
      type: object

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer                     
         

security:
  - bearerAuth: []
